; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g070rb]
platform = ststm32
board = nucleo_g070rb
framework = arduino
upload_protocol = stlink

build_flags = -DARCH_STM32

upload_flags =
    -c set_option_bytes 0x0

extra_scripts = post:gen_hex.py

lib_deps =
    https://github.com/stm32duino/STM32FreeRTOS.git
    marzogh/SPIMemory